# Tratamiento de imágenes y vídeos con OpenCV

<b>Fuentes:</b> 
1. [Tutoriales oficiales de OpenCV](https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html)
2. Joseph Howse and Joe Minichino, [Learning OpenCV 4 Computer Vision with Python3](https://learning-oreilly-com.bibproxy.ulpgc.es/library/view/learning-opencv-4/9781789531619/), Packt, 2020 (accesible en O'Reilly)
3. [OpenCV Course - Full Tutorial with Python](https://www.youtube.com/watch?v=oXlwWbU8l2o)


## Gestión de imágenes y vídeos

Lectura y escritura de imágenes y vídeos desde fichero y webcam.

In [1]:
#Lectura y Escritura de imágenes
import cv2 as cv

img = cv.imread('images/eii.png')
print(img.shape)
cv.imshow('Imagen', img)
#cv.imwrite('images/eii2.png', img)



(363, 452, 3)


In [2]:
# lectura de imágenes
import cv2 as cv
#import numpy as np

file = 'images/eii.png'
#image = cv.imread(file) #,cv.IMREAD_GRAYSCALE)
image = cv.imread(file,cv.IMREAD_GRAYSCALE)

cv.imshow('EII', image)

k = cv.waitKey(0)

if k==ord('s'):
    print('Guardamos la imagen')
    cv.imwrite('images/eiiprueba.png', image)

cv.destroyAllWindows()


Guardamos la imagen


In [3]:
# lectura de vídeos
import cv2 as cv
video = cv.VideoCapture('videos/times-square.mp4')

while True:
    state, frame = video.read()
    
    cv.imshow('Video', frame)
    
    if cv.waitKey(20)==27:
        break

video.release()
cv.destroyAllWindows()


In [7]:
# lectura de webcam
import cv2 as cv

video = cv.VideoCapture(0)

while True:
    state, frame = video.read()
    
    cv.imshow('Video', frame)
    
    if cv.waitKey(20)==27:
        break

video.release()
cv.destroyAllWindows()

error: OpenCV(4.8.1) /Users/xperience/GHA-OpenCV-Python/_work/opencv-python/opencv-python/opencv/modules/highgui/src/window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


## Dibujo de primitivas
1. Líneas
2. Rectángulos
3. Círculos
4. Elipses
5. Polígonos
6. Texto


In [ ]:
#Dibujando primitivas
import cv2 as cv
import numpy as np

w = 300
h = 50

image = cv.imread('images/eii.png')
cv.circle(image, (w,h), 25, (0,0,255), thickness=cv.FILLED)
#cv.line(image, (0,0), (500,100), (0,255,0), thickness=4)

cv.imshow('Punto',image)
#cv.imshow('Línea',image)

cv.waitKey(0)
cv.destroyAllWindows()



In [ ]:
#Dibujando primitivas
import cv2 as cv
import numpy as np

image = cv.imread('images/eii.png')

w = image.shape[1]//2
h = image.shape[0]//2

cv.line(image, (0,0), (w,h), (0,255,0), thickness=1)

cv.rectangle(image, (w,h), (w*2-30,h*2-30), (255,128,0), thickness=cv.FILLED)

cv.circle(image, (w,h), 50, (255,0,0), thickness=2)

cv.ellipse(image, (w//2,h),(100,50),45,0,360,(100,100,100),-1)

cv.putText(image, "Centro", (w,h), cv.FONT_HERSHEY_SIMPLEX, 1, (0,200,200), 2, cv.LINE_AA)

pts = np.array([[w+10,50],[w-25,85],[w+40,100],[w+140,80],[w+100,60]], np.int32)
print(pts)
pts = pts.reshape((-1,1,2))
print('***')
print(pts)
cv.polylines(image,[pts],True,(0,0,0),3)

cv.imshow('Primitivas',image)

key = cv.waitKey(0)

if key == 27:  
    cv.destroyAllWindows()
    cv.waitKey(1)



[[236  50]
 [201  85]
 [266 100]
 [366  80]
 [326  60]]
***
[[[236  50]]

 [[201  85]]

 [[266 100]]

 [[366  80]]

 [[326  60]]]


: 

## Interacción con el usuario
1. Uso de *trackbars*
2. Uso del ratón

In [ ]:
# Uso de un trackbar
import cv2 as cv

def trackbar(x):
    print(x)
    cv.imshow('EII', img)

img = cv.imread('images/eii.png', cv.IMREAD_COLOR)
cv.imshow('EII', img)
cv.createTrackbar('x', 'EII', 100, 255, trackbar)

key = cv.waitKey(0)
if key == 27:  
    cv.destroyAllWindows()
    cv.waitKey(1)

100


In [3]:
import cv2 as cv

# Uso de varios Trackbars
def trackbar(x):
    x = cv.getTrackbarPos('x', 'EII')
    y = cv.getTrackbarPos('y', 'EII')
    print(x,y)
    cv.imshow('EII', img)

img = cv.imread('images/eii.png')
cv.imshow('EII', img)

cv.createTrackbar('x', 'EII', 100, 255, trackbar)
cv.createTrackbar('y', 'EII', 100, 255, trackbar)

key = cv.waitKey(0)
if key == 27:  
    cv.destroyAllWindows()
    cv.waitKey(1)


100 -1
100 100
100 100
100 100
100 100
100 100
100 100
100 100
100 100
100 100
100 100
100 100
100 99
100 99
100 99
100 99
100 99
100 98
100 98
100 94
100 94
100 90
100 90
100 86
100 86
100 80
100 80
100 75
100 75
100 75
100 70
100 70
100 66
100 66
100 64
100 64
100 62
100 62
100 61
100 61
100 60
100 60
100 59
100 59
100 58
100 58
100 56
100 56
100 55
100 55
100 55
100 53
100 53
100 53
100 50
100 50
100 47
100 47
100 45
100 45
100 42
100 42
100 40
100 40
100 39
100 39
100 38
100 38
100 38
100 37
100 37
100 36
100 36
100 35
100 35
100 34
100 34
100 34
100 34
100 33
100 33
100 33
100 33
100 33
100 33
100 32
100 32
100 32
100 32
100 32
100 32
100 32
100 32
100 32
100 32
100 32
100 31
100 31
100 30
100 30
100 29
100 29
100 27
100 27
100 27
100 25
100 23
100 23
100 21
100 21
100 20
100 20
100 19
100 19
100 18
100 18
100 18
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 17
100 18
100 18
100 18
100 18
100 19
100 19
100 19
10

In [ ]:
import cv2 as cv

# Uso de varios Trackbars
def nothing(x):
    pass
   
img = cv.imread('images/eii.png')
cv.imshow('EII', img)

cv.createTrackbar('x', 'EII', 100, 255, nothing)
cv.createTrackbar('y', 'EII', 100, 255, nothing)

#cv.setTrackbarPos('x', 'EII', 111)
#cv.setTrackbarPos('y', 'EII', 222)


while True:
    cv.imshow('EII', img)   
    k = cv.waitKey(1)
    if k == 27:
        break
    x = cv.getTrackbarPos('x', 'EII')
    y = cv.getTrackbarPos('y', 'EII')
    print(x,y)
    
cv.destroyAllWindows()

In [ ]:
import numpy as np
import cv2 as cv
 
def nothing(x):
    pass
 
# Create una imagen negra en una ventana
img = np.zeros((300,512,3), np.uint8)
cv.namedWindow('image')
 
# crear trackbars para cambio de color
cv.createTrackbar('R','image',0,255,nothing)
cv.createTrackbar('G','image',0,255,nothing)
cv.createTrackbar('B','image',0,255,nothing)
 
# crear un interruptor para funcionalidad ON/OFF
switch = '0 : OFF \n1 : ON'
cv.createTrackbar(switch, 'image',0,1,nothing)
 
while(1):
    cv.imshow('image',img)
    k = cv.waitKey(1) & 0xFF
    if k == 27:
        break
 
    # Optener estado actual de los cuatro trackbacks
    r = cv.getTrackbarPos('R','image')
    g = cv.getTrackbarPos('G','image')
    b = cv.getTrackbarPos('B','image')
    s = cv.getTrackbarPos(switch,'image')
 
    if s == 0:
        img[:] = 0
    else:
        img[:] = [b,g,r]
 
cv.destroyAllWindows()

: 

In [ ]:
# Uso del ratón
import cv2 as cv
import numpy as np

def mouse(event, x, y, flags, param):
    text = f'{event} - ({x}, {y}), flags={flags}, param={param}'
    print(text)
    if flags==1:
        #img[y-1,x]=[255,0,0]
        #img[y,x]  =[255,0,0]
        #img[y+1,x]=[255,0,0]
        #img[y,x-1]=[255,0,0]
        #img[y,x+1]=[255,0,0]
        
        img[y,x]  =[0,255,0]
        img[y-1,x]=[0,255,0]
        img[y+1,x]=[0,255,0]
        img[y,x-1]=[0,255,0]
        img[y,x+1]=[0,255,0]
        img[y-2,x]=[0,255,0]
        img[y+2,x]=[0,255,0]
        img[y,x-2]=[0,255,0]
        img[y,x+2]=[0,255,0]
     
        #img[y-1,x]=[0,0,255]
        #img[y,x]  =[0,0,255]
        #img[y+1,x]=[0,0,255]
        #img[y,x-1]=[0,0,255]
        #img[y,x+1]=[0,0,255]
        
    cv.imshow('EII', img)

img = cv.imread('images/eii.png')
#img = 255*np.ones((480,640,3), np.uint8)

cv.imshow('EII', img)

cv.setMouseCallback('EII', mouse)

key = cv.waitKey(0)

if key == 27:  
    cv.destroyAllWindows()
    cv.waitKey(1)

0 - (391, 278), flags=0, param=None
0 - (389, 276), flags=0, param=None
0 - (386, 272), flags=0, param=None
0 - (384, 269), flags=0, param=None
0 - (384, 268), flags=0, param=None
0 - (382, 266), flags=0, param=None
0 - (381, 265), flags=0, param=None
0 - (381, 264), flags=0, param=None
0 - (381, 263), flags=0, param=None
0 - (381, 263), flags=0, param=None
0 - (381, 263), flags=0, param=None
1 - (381, 263), flags=1, param=None
4 - (381, 263), flags=1, param=None
0 - (380, 267), flags=0, param=None
0 - (377, 276), flags=0, param=None
0 - (370, 291), flags=0, param=None
0 - (363, 306), flags=0, param=None
0 - (360, 313), flags=0, param=None
0 - (356, 322), flags=0, param=None
0 - (353, 328), flags=0, param=None
0 - (351, 332), flags=0, param=None
0 - (351, 333), flags=0, param=None
0 - (351, 333), flags=0, param=None
0 - (351, 333), flags=0, param=None
0 - (351, 332), flags=0, param=None
0 - (351, 331), flags=0, param=None
0 - (351, 330), flags=0, param=None
0 - (352, 329), flags=0, par

In [2]:
#Trackbar para cambiar un eje de color
import cv2 as cv #BGR
import numpy as np

def trackbar(x):
    img[:, :, 2] = x
    cv.imshow('Mapa de Colores', img)

img = np.zeros((256, 256, 3), dtype=np.uint8)
for i in range(256):
    img[i, :, 0] = i
    img[:, i, 1] = i
    
cv.imshow('Mapa de Colores', img)

cv.createTrackbar('red', 'Mapa de Colores', 0, 255, trackbar)

key = cv.waitKey(0)

if key == 27:  
    cv.destroyAllWindows()
    cv.waitKey(1)